### ISSUE TITLE
Parameter -x-total-time-out does not work

### ISSUE THREAD

**Issue by FahimehBahrami** [forsyde/IDeSyDe#17]
IDeSyDe does not stop working after the time set as the total time out. It finds some solutions and tries to find more solutions and never finishes. I set the total time out to 60 seconds and waited till 1 hour, and it still did not finish.

**Comment by Rojods** [comment]
Correct. It was a mistake in the source code that prevented it from aggressively finishing the cooperative exploration algorithm. This has been fixed since version 0.7.4.
