### ISSUE TITLE
The actor with special requirements is not mapped to the accelerator which is considered to host that actor

### ISSUE THREAD

**Issue by FahimehBahrami** [forsyde/IDeSyDe#18]
In my synchronous application model, one of the actors, SobelSY, is supposed to be mapped to an accelerator tile. To do so, I have set the computational requirements in the ForSyDe IO model of the application as follows:
`"computationalRequirements": {
      "impl1": {
        "sobel": 1.0_64
      }
    },`
And in the ForSyDe IO model of the platform, for the accelerator tile, the provided resources are annotated as follows:
`"modalInstructionsPerCycle": {
      "default": {
        "sobel": 1.0_64
      }
    }`
The issue is that IDeSyDe does not go further than the "client handshake" phase.

**Comment by Rojods** [comment]
Yes, this is actually a problem with ForSyDe IO. We can ask the devs there to add a feature where the model loading passes only of the model is fully consistent. IDeSyDe cannot do much except trust that the model returned By ForSyDe IO is correctly loaded.
