### ISSUE TITLE
IDeSyDe cannot find bindings for graphs that it could find bindings for before

### ISSUE THREAD

**Issue by FahimehBahrami** [forsyde/IDeSyDe#19]
Version 0.7.5 of IDeSyDe cannot find any binding for graphs that previous versions could find bindings for.

**Comment by Rojods** [comment]
In principle, this issue has been resolved with hot fixes and will make in to version 0.7.6. To be double checked later.

**Comment by Rojods** [comment]
Close as likely resolved since the problem has not appeared again.
