### ISSUE TITLE
Exploration is never performed despite a bidding

### ISSUE THREAD

**Issue by BeethovenKodar** [forsyde/IDeSyDe#21]
Running IDeSyDe from the `develop` branch identifies the decision models and receives a bidding from the Jenetics explorer, but then the exploration fails silently (implied by 0ms exploration time) and with `-v DEBUG` some errors are listed.

Platform: 
[MPSoC.txt](https://github.com/forsyde/IDeSyDe/files/14945895/MPSoC.txt)

Application:
[ToySDF.txt](https://github.com/forsyde/IDeSyDe/files/14945900/ToySDF.txt)

Output from IDeSyDe:
[out.txt](https://github.com/forsyde/IDeSyDe/files/14945999/out.txt)

**Comment by BeethovenKodar** [comment]
I'm not sure if this still is a bug. I tried reproducing it just now and see no issue with `develop` commit 265975.

**Comment by Rojods** [comment]
It was an issue which I managed to isolate and solve :). It had to do with some corner-cases destroying the identification rules for gathering SDF applications.
