### ISSUE TITLE
Implement part() in HardwareImplementationArea decision model

### ISSUE THREAD

**Issue by BeethovenKodar** [forsyde/IDeSyDe#29]
"part() being empty may introduce some hard-to-trace unwanted behaviours later if we have multiple decision models partially identifying the same set of elements" -Rodolfo

With this said, implementing `part()` may be relevant

**Comment by Rojods** [comment]
It was added in the last commit [3c6531c](https://github.com/forsyde/IDeSyDe/commit/3c6531c367740e02ff770f219789c86f567b53dd) within the `proglogic` branch!
