### ISSUE TITLE
Specifying token size for an SDFChannel crashes the PL decision model

### ISSUE THREAD

**Issue by BeethovenKodar** [forsyde/IDeSyDe#34]
Same platform as in `examples_and_benchmarks/novel/programmable_logic_area/MPSoC_Final.fiodl` and application is attached

[evaluatorsdf.txt](https://github.com/forsyde/IDeSyDe/files/15389574/evaluatorsdf.txt)

Running idesyde with these input files produces 
```
thread '<unnamed>' panicked at rust-bridge-minizinc/src/lib.rs:790:38:
Should not fail to parse the output of minizinc: Error("missing field `output`", line: 1, column: 2155)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Rayon: detected unexpected panic; aborting
./run.sh: line 60: 1070663 Aborted                 (core dumped) ./$DSE_EXECUTABLE -v DEBUG -p 5 --x-total-time-out 30 $plat $appl
```

**Comment by Rojods** [comment]
I made a silly mistake in the indexing of the Minizinc side within the decision model. I think the latest `develop` commit has fixed the issue! Could you check it out, please? :)

**Comment by Rojods** [comment]
Gotcha, will take a look at them!

**Comment by Rojods** [comment]
Good news is that I already discovered why tc1 fails: the time to transfer data in the interconnects is gigantic, and my number scaling has not properly accounted for huge numbers in the interconnect, only in the computation and memories!

For tc3, I am still investigating. It complains of inconsistency without further info, so  that's not nice, but we will manage.

**Comment by Rojods** [comment]
@BeethovenKodar  I made some small breakthrough in the debugging here: it seems the greatest enemy we have now is that the FPGA element in the `MPSoC_Final` model _cannot_ reach back any memory to write it there. So, there are a couple things that could have gone wrong here:

1. The model is actually wrong in the sense that there is no directional interconnect path from a FPGA to a memory element.
2. We messed up the path-constructing logic in the identification rule.

Could you please check out that 1) is not true, please? :)

**Comment by BeethovenKodar** [comment]
I just pushed a new mpsoc version ti the examples. The previous one was strange. See if this fixes it, I can check the specified connections in the meantime!

**Comment by BeethovenKodar** [comment]
There are three two-way connections from the FPGA, of which one connects to the PL DDR4 switch (memory switch). 

Like, this used to work so the issue feels unrelated but who knows right.

**Comment by Rojods** [comment]
I guess it used to work because in some previous commits i was not enforcing that the mapping would 100% respect the paths in the interconnection. Now it does! So that could be the change that suddenly made us not have the solutions anymore. I'll try soon the new model and see!

**Comment by BeethovenKodar** [comment]
I realized my one-way connections had the wrong `EdgeTrait`, does it help with anything? I pushed the change anyhow.

**Comment by Rojods** [comment]
It did help! There was also another subtle mistake in the IRule identifying the new hardware model (`MMCore...`). Now the only failing case is `tc3`. BUT, I think the mistake is something a bit funnier: did you see that one of the actors actually requires mores BRAM than the FPGA provides? Is this in purpose? So that no solution exists? 
This same exact thing happens with the "Area" requirement of the other actor. 

If you change this to some smaller zeroes, it works!

**Comment by Rojods** [comment]
I just added a feasible version of `tc3` with this feasibility: `tc3_feasible`.

**Comment by BeethovenKodar** [comment]
Hahah yes it is meant to fail!!

**Comment by BeethovenKodar** [comment]
![image](https://github.com/forsyde/IDeSyDe/assets/55529498/6edadc3a-5390-4064-812e-2a55f4d956a6)

**Comment by Rojods** [comment]
Well, we can accept crash as passing :P. I am not sure if it still crash or the latest commits just finishes with no solution. I might try to pretty it out later.

**Comment by BeethovenKodar** [comment]
Results are in for the test cases finally! No need to fix the crash as it is _perfectly_ fine as there is a strong correlation to exceeding the limits.

**Comment by Rojods** [comment]
Since we seem to have fixed this issue for now, I will close it :).
