### ISSUE TITLE
Add superloops and "real" throughput to PL's reverse identification

### ISSUE THREAD

**Issue by BeethovenKodar** [forsyde/IDeSyDe#37]
As the title states. These should be reusable from other exploration modules.

**Comment by Rojods** [comment]
The latest `develop` (087c4789e9eb0fa335cbd5cb84e9edf1482d0cc7) should have fixed that :). At least it does fix them in many of my local tests! Could you check out if it also fixes when you rebuild on your machine? So we know it is a real fix.

**Comment by BeethovenKodar** [comment]
This surely works too. However, the throughput is _not_ the same between actors, but they are multiples so this could be the reason behind it :)

**Comment by Rojods** [comment]
You are 100% correct. If during an application cycle, or application epoch (whatever you wanna call it), one actor fires 1 time and another fires 5 times, it naturally means that the throughput (firings per second) of one actor is 5 times higher than the other! The numbers IDeSyDe output are a normalized inverse number that indirectly tracks the actual throughput numbers but are quite more useful during optimisation.
