### ISSUE TITLE
Buffer sizes not part of reverse identification

### ISSUE THREAD

**Issue by BeethovenKodar** [forsyde/IDeSyDe#38]
I've realized that buffer sizes are not part of the reversed input models. The input I'm using is `MPSoC_Final.fiodl` and `tc1.fiodl`. The input application specifies the `BufferLike` trait and sets `"elementSizeInBits": 8_l`.

**Comment by BeethovenKodar** [comment]
Does work nicely. I don't know if the number of tokens in the buffer is correct, but for what I created this issue for we can definitely close! :)

**Comment by Rojods** [comment]
I have checked the number of tokens against the "designer expected" number and it seemed right! So I will close this as solved :)
